SELECT * FROM "MEMBER";


-- 이메일 중복 검사
SELECT COUNT(*)  
FROM "MEMBER"
WHERE MEMBER_EMAIL = 'user01@mail.com';


SELECT * FROM "MEMBER";
SELECT * FROM "MEMBER_INFO";


--컬럼 추가 1
--ALTER TABLE	"MEMBER" ADD MEMBER_BIRTH VARCHAR(10);

--ALTER TABLE "MEMBER" ADD MEMBER_GEN CHAR(1);

--컬럼 추가 2 (기본 값, NOT NULL 지정)
 ALTER TABLE "MEMBER" ADD MEMBER_BIRTH VARCHAR(10) DEFAULT '19450815' NOT NULL;
 ALTER TABLE "MEMBER" ADD MEMBER_GEN CHAR(1) DEFAULT 'F' NOT NULL;

--컬럼 삭제
ALTER TABLE "MEMBER" DROP COLUMN MEMBER_BIRTH;
ALTER TABLE "MEMBER" DROP COLUMN MEMBER_GEN;



-- 이메일 인증
DROP TABLE "AUTH_KEY";

CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_NO"	NUMBER		NOT NULL,
	"CODE"	CHAR(6)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO" IS '인증키 구분 번호(SEQ_AUTH_KEY_NO)';

COMMENT ON COLUMN "AUTH_KEY"."CODE" IS '코드';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '이메일';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 코드 생성 시간';

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"AUTH_KEY_NO"
);

-- alt + x

CREATE SEQUENCE SEQ_AUTH_KEY_NO NOCACHE;


UPDATE "AUTH_KEY" SET
CODE = #{authkey},
CREATE_TIME = sysdate
WHERE EMAIL = #{email};

INSERT INTO "AUTH_KEY" VALUES(SEQ_AUTH_KEY_NO.NEXTVAL, #{authkey}, #{email}, DEFAULT);

SELECT * FROM "AUTH_KEY";

--INSERT INTO	"MEMBER_INFO"(MEMBER_NO,INFO_GENDER,INFO_BIRTH)
--VALUES (회원번호, #{infoGender},#{infoBirth})



-- user01의 비밀번호 변경
--UPDATE "MEMBER" SET
--MEMBER_PW = '$2a$10$Bpolx5IpJ6Kzz5q/tAb6X.rqEugZuqEiEqMUomuyFft.xiwFK9uVS';

-- 비밀번호 조회
SELECT MEMBER_PW FROM "MEMBER" 		
WHERE MEMBER_NO = 314;

-- 비밀번호 변경
UPDATE "MEMBER"
	SET MEMBER_PW = 1234
	WHERE MEMBER_NO = 314;

COMMIT;


ROLLBACK;

UPDATE "MEMBER"
SET MEMBER_PW = '123456#'
WHERE MEMBER_EMAIL = 'meso8587@naver.com'
AND DISABLE_DATE IS NOT NULL  
;

SELECT TO_DATE('2023-05-25','YYYY-MM-DD') FROM DUAL;



DELETE FROM "MEMBER" WHERE MEMBER_NO  = 97;
COMMIT ;

SELECT * FROM "MEMBER"  ;

INSERT INTO "MEMBER" 
VALUES(
	SEQ_MEMBER_NO.NEXTVAL, 	-- 회원번호
	'@nate.com', 					-- 이메일
	'$2a$10$DOTDled.2j4/7uWiWgsxGOBFSaLXaHGFpQdbJqFKIl3XWl84sMevG', 			-- 비밀번호
	'안한수',	 					-- 이름
	'01054112359',						-- 전화번호
	DEFAULT, 				-- 계정상태(N:정상(기본), B:비활성, D:탈퇴)
	DEFAULT, 				-- 가입일(기본:SYSDATE)
	NULL, 					-- 비활성화일
	NULL, 					-- 탈퇴일
	DEFAULT, 				-- 친구요청(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 개인피드설정(A:모두(기본), F:친구만, M:나만)
	DEFAULT, 				-- 친구요청알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 친구신청수락알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 태그알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글댓글알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글좋아요알림(N:OFF, Y:ON(기본))
	DEFAULT, 				-- 게시글공유알림(N:OFF, Y:ON(기본))
	DEFAULT					-- 개인피드갱신알림(N:OFF, Y:ON(기본))
);


INSERT INTO "MEMBER_INFO" (MEMBER_NO)
VALUES (SEQ_MEMBER_NO.CURRVAL);

COMMIT;


SELECT * FROM "MEMBER"
WHERE MEMBER_NAME ='정대만';

SELECT * FROM "MEMBER" ;




























