SELECT * FROM "MEMBER";


-- 이메일 중복 검사
SELECT COUNT(*)  
FROM "MEMBER"
WHERE MEMBER_EMAIL = 'user01@mail.com';


SELECT * FROM "MEMBER";
SELECT * FROM "MEMBER_INFO";


--컬럼 추가 1
--ALTER TABLE	"MEMBER" ADD MEMBER_BIRTH VARCHAR(10);

--ALTER TABLE "MEMBER" ADD MEMBER_GEN CHAR(1);

--컬럼 추가 2 (기본 값, NOT NULL 지정)
 ALTER TABLE "MEMBER" ADD MEMBER_BIRTH VARCHAR(10) DEFAULT '19450815' NOT NULL;
 ALTER TABLE "MEMBER" ADD MEMBER_GEN CHAR(1) DEFAULT 'F' NOT NULL;

--컬럼 삭제
ALTER TABLE "MEMBER" DROP COLUMN MEMBER_BIRTH;
ALTER TABLE "MEMBER" DROP COLUMN MEMBER_GEN;



-- 이메일 인증
DROP TABLE "AUTH_KEY";

CREATE TABLE "AUTH_KEY" (
	"AUTH_KEY_NO"	NUMBER		NOT NULL,
	"CODE"	CHAR(6)		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY_NO" IS '인증키 구분 번호(SEQ_AUTH_KEY_NO)';

COMMENT ON COLUMN "AUTH_KEY"."CODE" IS '코드';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '이메일';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 코드 생성 시간';

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"AUTH_KEY_NO"
);

-- alt + x

CREATE SEQUENCE SEQ_AUTH_KEY_NO NOCACHE;


UPDATE "AUTH_KEY" SET
CODE = #{authkey},
CREATE_TIME = sysdate
WHERE EMAIL = #{email};

INSERT INTO "AUTH_KEY" VALUES(SEQ_AUTH_KEY_NO.NEXTVAL, #{authkey}, #{email}, DEFAULT);

SELECT * FROM "AUTH_KEY";

INSERT INTO	"MEMBER_INFO"(MEMBER_NO,INFO_GENDER,INFO_BIRTH)
VALUES (회원번호, #{infoGender},#{infoBirth})








