
SELECT * FROM TB_STUDENT ts ;

SELECT * FROM TB_DEPARTMENT;

-- 1.
SELECT DEPARTMENT_NAME 학과명,CATEGORY 계열 
FROM TB_DEPARTMENT;

-- 2. 
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' 
FROM TB_DEPARTMENT;
-- || : +

-- 3.
SELECT STUDENT_NAME
FROM TB_DEPARTMENT 
JOIN TB_STUDENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '001'
AND ABSENCE_YN = 'Y'
AND SUBSTR( STUDENT_SSN,8,1) = '2';

-- 4.
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;

-- 5.
SELECT DEPARTMENT_NAME,CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY  BETWEEN 20 AND 30;


-- 6.
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO  IS NULL ;
-- 소속된 학과가 없는(IS NULL) 교수찾기 


-- 7.
SELECT STUDENT_NAME  
FROM TB_STUDENT 
WHERE DEPARTMENT_NO IS NULL;

-- 8.
SELECT CLASS_NO 
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO  IS NOT NULL ;


--9.
SELECT CATEGORY
FROM TB_DEPARTMENT;

--10.
SELECT STUDENT_NO ,STUDENT_NAME ,STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'N'
AND STUDENT_ADDRESS LIKE '전주%'
AND STUDENT_NO LIKE 'A2%'; 





--1
SELECT STUDENT_NO AS 학번 , STUDENT_NAME AS 이름 ,ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;
-- DESC 내림차순


--2
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3; 

-- 문자열 글자수 : LENGTH(컬럼명)
-- 문자열 바이트수 : LENGTHB  영어/숫자/특수문자 1byte 한글 3byte

--3
SELECT PROFESSOR_NAME 교수이름, TRUNC(MONTHS_BETWEEN(SYSDATE ,TO_DATE(19||SUBSTR(PROFESSOR_SSN,0,6),'yyyymmdd'))/12) 나이 -- 1살지나려면 12달이 지나야하니까 
FROM TB_PROFESSOR 																				-- yyyy-mm-dd 오류 왜냐하면 TO_DATE(19방식에 - (부호)가 표시되지 않았기 때문)		
WHERE SUBSTR(PROFESSOR_SSN,8,1)='1'
ORDER BY 나이 ASC ;

-- MONTHS_BETWEEN (날짜1, 날짜2) :  두 날짜의 월 차이를 계산해서, 개월 수를 산출할 때 사용
-- 개월 수 소수점 절사 (TRUNC) 사용  소수점 아래는 TRUNC 함수를 사용하여 절사하고 실제 개월 수만 사용
-- 상황에 따라서 ROUND 함수를 사용하여 소수점을 반올림하여 사용할 수도 있다.
-- 음수부호가 나올 경우 절대 값 ABS 함수을 이용.

-- 4
SELECT SUBSTR(PROFESSOR_NAME,2,2)이름
FROM TB_PROFESSOR ;

-- 5
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT 
WHERE TO_NUMBER(TO_CHAR(ENTRANCE_DATE,'yyyy')) -TO_NUMBER(19||(SUBSTR(STUDENT_SSN ,0,2))) >19;
																	

-- yy : 100년단위 계산 --> 2000년 1월 1일 부터 2099년 12월 31일까지
-- RR : 50년을 기준 --> 1950년 1월 1일 부터 2049년 12월 31일 




  









































