-- MEMBER 테이블 삭제
DROP TABLE MEMBER;

-- 회원제 게시판

-- 회원(MEMBER) 테이블

CREATE TABLE "MEMBER"( -- 테이블명 만들 때는 "" 가 넣어주는게 좋음
	  MEMBER_NO NUMBER CONSTRAINT MEMBER_PK PRIMARY KEY,
	  MEMBER_ID VARCHAR2(30) NOT NULL,
	  MEMBER_PW VARCHAR2(30) NOT NULL,
	  MEMBER_NM VARCHAR2(30) NOT NULL,
	  MEMBER_GENDER CHAR(1)  
	  CONSTRAINT GENDER_CHK CHECK(MEMBER_GENDER IN('M','F')),
	  ENROLL_DT DATE DEFAULT SYSDATE NOT NULL,
	  UNREGISTER_FL CHAR(1) DEFAULT 'N'
	  CONSTRAINT UNREGISTER_CHECK CHECK(UNREGISTER_FL IN('Y','N'))
);


-- 게시글(BOARD) 테이블


-- 댓글(COMMENT) 테이블



