
SELECT * FROM TB_STUDENT ts ;

SELECT * FROM TB_DEPARTMENT;

-- 1.
SELECT DEPARTMENT_NAME 학과명,CATEGORY 계열 
FROM TB_DEPARTMENT;

-- 2. 
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY || '명 입니다.' 
FROM TB_DEPARTMENT;
-- || : +

-- 3.
SELECT STUDENT_NAME
FROM TB_DEPARTMENT 
JOIN TB_STUDENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = "001"
AND ABSENCE_YN = "Y"
AND SUBSTR( STUDENT_SSN,8,1) = "2";

-- 4.
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN ("A513079","A513090","A513091","A513110", "A513119")
ORDER BY STUDENT_NAME DESC;

-- 5.
SELECT DEPARTMENT_NAME ,CATEGORY,CAPACITY 
FROM TB_DEPARTMENT
BETWEEN 20 AND 30
ORDER BY DEPARTMENT_NAME;

-- 6.

FROM TB_






