SELECT * FROM "MEMBER" ;

SELECT *
FROM "BOARD"
WHERE COUNTRY_NO = 1;

SELECT * FROM BOARD 
WHERE BOARD_NO =170;

SELECT * FROM TAG ;

INSERT INTO BOARD 
VALUES (SEQ_BOARD_NO.NEXTVAL, '아아아','박종욱',DEFAULT,DEFAULT,DEFAULT,DEFAULT,11,1,2,NULL,NULL);

ROLLBACK;

 SELECT * FROM BOARD_TYPE
 WHERE BOARD_CODE = 2
 ORDER BY BOARD_CODE ;
 

SELECT * FROM BOARD
ORDER BY board_no DESC;


-- 게시글 수정 자유/질문
UPDATE "BOARD" SET
BOARD_TITLE = '잘가라',
BOARD_TEXT  = '진짜 간다',
UPDATE_DATE = SYSDATE 
WHERE BOARD_CODE = 2
AND BOARD_NO = 186;

COMMIT;

-- 게시글 수정 자유/질문
UPDATE "BOARD" SET
BOARD_TITLE = '마오쩌둥',
BOARD_TEXT  = '공산주의만세',
UPDATE_DATE = SYSDATE 
WHERE BOARD_CODE = 1
AND COUNTRY_NO = 1
AND BOARD_NO = 184;

COMMIT;

-- 자유/질문 게시판 
SELECT * 
FROM BOARD_TYPE 
WHERE BOARD_CODE= 2
OR  BOARD_CODE =3
OR BOARD_CODE =1;



SELECT * FROM BOARD_TYPE
WHERE BOARD_CODE =1
or BOARD_CODE =2
ORDER BY BOARD_CODE ASC;

SELECT * FROM COUNTRY c ;

SELECT * FROM COUNTRY 
WHERE COUNTRY_NO = 1
OR  COUNTRY_NO = 2 
OR  COUNTRY_NO = 3
OR COUNTRY_NO = 4
OR COUNTRY_NO = 5
ORDER BY COUNTRY_NO ASC ;


SELECT * FROM TAG  
WHERE TAG_NO  = 1
OR  TAG_NO = 2 
OR  TAG_NO = 3
OR TAG_NO = 4
ORDER BY TAG_NO ASC ;


SELECT BOARD_CODE, BOARD_NAME FROM (
	SELECT BOARD_TYPE.* , '1' TEMP FROM BOARD_TYPE 
	WHERE BOARD_CODE NOT IN (1,4)
	UNION 
	SELECT COUNTRY.*, '2' TEMP FROM COUNTRY 
	WHERE COUNTRY_NO != 0
)
ORDER BY TEMP, BOARD_CODE;



