SELECT * FROM "MEMBER" ;

SELECT *
FROM "BOARD"
WHERE COUNTRY_NO = 1;

SELECT * FROM BOARD ;

SELECT * FROM TAG ;

INSERT INTO BOARD 
VALUES (SEQ_BOARD_NO.NEXTVAL, '아아아','박종욱',DEFAULT,DEFAULT,DEFAULT,DEFAULT,11,1,2,NULL,NULL);

ROLLBACK;

 SELECT * FROM BOARD_TYPE
 WHERE BOARD_CODE = 2
 ORDER BY BOARD_CODE ;